language: go

go: "1.13"

env: GO111MODULE=on

notifications:
  email: false

before_script:
  - docker build -t db --file `pwd`/build/db.Dockerfile .
  - docker run -d -p 5432:5432 db
  - go mod tidy

script:
  - sleep 15
  - go test ./...