version: "3.3"

services:

  database:

    build:
      context: .
      dockerfile: ./build/db.Dockerfile

  main:
    build:
      context: .
      dockerfile: build/main.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage

    depends_on:
      - database
      - auth
      - user

  auth:
    build:
      context: .
      dockerfile: build/auth.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage

    depends_on:
      - database

  chat:
    build:
      context: .
      dockerfile: ./build/chat.Dockerfile

    volumes:
      - type: bind
        source: ../static
        target: /static

    depends_on:
      - database
      - auth

  user:
    build:
      context: .
      dockerfile: ./build/user.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage

    depends_on:
      - database

  nginx:
    image: nginx:1.15.3

    restart: unless-stopped

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    links:
      - main:main
      - chat:chat

    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - ../static:/static
      - ../storage:/storage
      - ../cert:/etc/ssl

    ports:
      - 80:80
      - 443:443

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - nginx:nginx

    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always

