version: "3.3"

services:

  main:

    build:
      context: .
      dockerfile: build/main.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage

    network_mode: host
    #ports:
     # - 8000:8000

    #depends_on:
     # - database

  chat:

    build:
      context: .
      dockerfile: ./build/chat.Dockerfile

    network_mode: host
    #ports:
     # - 8000:8000

    #depends_on:
     # - database


  #database:

   # build:
      #context: .
     # dockerfile: ./build/db.Dockerfile

    #ports:
    #  - 5432:5432

  nginx:
    image: nginx:1.15.3

    #links:
    #  - main:main
    #  - chat:chat
    network_mode: host

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/static
      - ../storage:/storage

    ports:
      - 80:80