version: "3.3"

services:

  main:

    build:
      context: .
      dockerfile: build/main.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage


    depends_on:
      - database
      - auth
      - user

  auth:

    build:
      context: .
      dockerfile: build/auth.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage
    depends_on:
      - database

  chat:

    build:
      context: .
      dockerfile: ./build/chat.Dockerfile

    depends_on:
      - database
      - auth

  user:

    build:
      context: .
      dockerfile: ./build/user.Dockerfile

    volumes:
      - type: bind
        source: ../storage
        target: /storage

    depends_on:
      - database


  database:

    build:
      context: .
      dockerfile: ./build/db.Dockerfile

  nginx:
    image: nginx:1.15.3

    links:
      - main:main
      - chat:chat

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/static
      - ../storage:/storage

    ports:
      - 80:80


  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - main
      - nginx

    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always

