version: "3"

services:

  backend:

    build: .

    ports:
      - 8000:8000

    depends_on:
      - database


  database:

    build: ./internal/pkg/database

    ports:
      - 5432:5432

  nginx:
    image: nginx:1.15.3

    links:
      - backend:backend

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/html

    ports:
      - 80:80