version: "3"

services:

  main:

    build:
      context: .
      dockerfile: build/main.Dockerfile

    volumes:
      - ../static:/static
      - ../storage:/storage

    ports:
      - 8000:8000

    depends_on:
      - database

  chat:

    build:
      context: .
      dockerfile: ./build/chat.Dockerfile

    volumes:
      - ../static:/static
      - ../storage:/storage

    ports:
      - 8001:8000

    depends_on:
      - database


  database:

    build:
      context: .
      dockerfile: ./build/db.Dockerfile

    environment:
      PGDATA: /var/lib/postgresql/data/pgdat

    volumes:
      - /var/lib/postgresql/10/main:/var/lib/postgresql/10/main

    ports:
      - 5432:5432

  nginx:
    image: nginx:1.15.3

    links:
      - main:main

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/static
      - ../storage:/storage

    ports:
      - 80:80