// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/list/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	models "2020_1_Color_noise/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIRepository is a mock of IRepository interface
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetMainList mocks base method
func (m *MockIRepository) GetMainList(start, limit int) ([]*models.Pin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainList", start, limit)
	ret0, _ := ret[0].([]*models.Pin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainList indicates an expected call of GetMainList
func (mr *MockIRepositoryMockRecorder) GetMainList(start, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainList", reflect.TypeOf((*MockIRepository)(nil).GetMainList), start, limit)
}

// GetSubList mocks base method
func (m *MockIRepository) GetSubList(id uint, start, limit int) ([]*models.Pin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubList", id, start, limit)
	ret0, _ := ret[0].([]*models.Pin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubList indicates an expected call of GetSubList
func (mr *MockIRepositoryMockRecorder) GetSubList(id, start, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubList", reflect.TypeOf((*MockIRepository)(nil).GetSubList), id, start, limit)
}

// GetRecommendationList mocks base method
func (m *MockIRepository) GetRecommendationList(id uint, start, limit int) ([]*models.Pin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecommendationList", id, start, limit)
	ret0, _ := ret[0].([]*models.Pin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecommendationList indicates an expected call of GetRecommendationList
func (mr *MockIRepositoryMockRecorder) GetRecommendationList(id, start, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecommendationList", reflect.TypeOf((*MockIRepository)(nil).GetRecommendationList), id, start, limit)
}
