# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_pb2 as image__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/image.ImageService/Analyze',
                request_serializer=image__pb2.Address.SerializeToString,
                response_deserializer=image__pb2.Tags.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=image__pb2.Address.FromString,
                    response_serializer=image__pb2.Tags.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageService/Analyze',
            image__pb2.Address.SerializeToString,
            image__pb2.Tags.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
