# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='image',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bimage.proto\x12\x05image\"\x18\n\x07\x41\x64\x64ress\x12\r\n\x05Image\x18\x01 \x01(\t\"\x14\n\x04Tags\x12\x0c\n\x04Tags\x18\x01 \x03(\t28\n\x0cImageService\x12(\n\x07\x41nalyze\x12\x0e.image.Address\x1a\x0b.image.Tags\"\x00\x62\x06proto3'
)




_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='image.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='image.Address.Image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=46,
)


_TAGS = _descriptor.Descriptor(
  name='Tags',
  full_name='image.Tags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Tags', full_name='image.Tags.Tags', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Tags'] = _TAGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.Address)
  })
_sym_db.RegisterMessage(Address)

Tags = _reflection.GeneratedProtocolMessageType('Tags', (_message.Message,), {
  'DESCRIPTOR' : _TAGS,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.Tags)
  })
_sym_db.RegisterMessage(Tags)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='image.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=70,
  serialized_end=126,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyze',
    full_name='image.ImageService.Analyze',
    index=0,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_TAGS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
