// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/session/usecase/usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "pinterest/internal/models"
	reflect "reflect"
)

// MockISessionUsecase is a mock of ISessionUsecase interface
type MockISessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockISessionUsecaseMockRecorder
}

// MockISessionUsecaseMockRecorder is the mock recorder for MockISessionUsecase
type MockISessionUsecaseMockRecorder struct {
	mock *MockISessionUsecase
}

// NewMockISessionUsecase creates a new mock instance
func NewMockISessionUsecase(ctrl *gomock.Controller) *MockISessionUsecase {
	mock := &MockISessionUsecase{ctrl: ctrl}
	mock.recorder = &MockISessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockISessionUsecase) EXPECT() *MockISessionUsecaseMockRecorder {
	return m.recorder
}

// CreateSession mocks base method
func (m *MockISessionUsecase) CreateSession(id uint) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", id)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession
func (mr *MockISessionUsecaseMockRecorder) CreateSession(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockISessionUsecase)(nil).CreateSession), id)
}

// CreateToken mocks base method
func (m *MockISessionUsecase) CreateToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateToken indicates an expected call of CreateToken
func (mr *MockISessionUsecaseMockRecorder) CreateToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockISessionUsecase)(nil).CreateToken))
}

// GetByCookie mocks base method
func (m *MockISessionUsecase) GetByCookie(cookie string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCookie", cookie)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCookie indicates an expected call of GetByCookie
func (mr *MockISessionUsecaseMockRecorder) GetByCookie(cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCookie", reflect.TypeOf((*MockISessionUsecase)(nil).GetByCookie), cookie)
}

// UpdateToken mocks base method
func (m *MockISessionUsecase) UpdateToken(session *models.Session, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", session, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToken indicates an expected call of UpdateToken
func (mr *MockISessionUsecaseMockRecorder) UpdateToken(session, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockISessionUsecase)(nil).UpdateToken), session, token)
}

// Delete mocks base method
func (m *MockISessionUsecase) Delete(cookie string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", cookie)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockISessionUsecaseMockRecorder) Delete(cookie interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockISessionUsecase)(nil).Delete), cookie)
}
